# Generated by Django 3.1.7 on 2021-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('mno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('accno', models.IntegerField(blank=True, null=True)),
                ('atmno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_master',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('accno', models.IntegerField()),
                ('rdate', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('bal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'record_master',
            },
        ),
    ]
