# Generated by Django 3.1.7 on 2021-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0002_auto_20210328_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='atmno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='accno',
            field=models.BigIntegerField(),
        ),
    ]
